### PR TITLE
Display local strategy usernames if found

### LINKED ISSUE #832: Improve the user list UI
## Feature description

We should display the username from the local strategy because UUID only are not human-readable.

Adding a small action to copy the ID could be nice as well.

### PR DESCRIPTION
**Pull request by Leodau**
## What does this PR do ?
As the title suggests, on the **Security:Users** page, display the user local strategy `username` as the list item title **if one is found**.

### How should this be manually tested?
Clone, Serve and [head to the users page](http://localhost:8080/#/security/users) to see that user items can now be easily identified.

image

Closes #832

### CODE REVIEW

**Review by Aschen — COMMENTED** [review]
It's confusing to me because it means that the user view is the only one that does not display document IDs in the AC.

Also sometime this view will displays IDs and sometime local strategy usernames.

I think we should rather display the username alongside the ID if it exists

**Review by xbill82 — APPROVED** [review]

**Review by Aschen — CHANGES_REQUESTED** [review]
It's confusing to me because it means that the user view is the only one that does not display document IDs in the AC.

Also sometime this view will displays IDs and sometime local strategy usernames.

I think we should rather display the username alongside the ID if it exists

**Comment by xbill82** [comment]
Ah, @Aschen good idea!

**Comment by Leodau** [comment]
> Ah, @Aschen good idea!

Makes sense to me, the thing is… we don't have tons of space to begin with :grimacing: 
image

**Comment by Aschen** [comment]
Maybe we could have a switch between "Display kuid" and "Display auth local" ?

**Comment by xbill82** [comment]
@Leodau I'd prefer a little design effort in order to show them both. We can play with the shades of grey (username matte black and ID grey just below and tiny, for example). And we can ask advice to @jsatge !

**Comment by berthieresteban** [comment]
Is the profiles information absolutely necessary there ?
There is my analysis:
  - The username information is more important than the profiles information because in that list we want to find quickly the user we are searching for, also to see user content we need to expand the div where we can find the profiles information
  - Actually, the kuid is always displayed entirely but the profiles section can grow up based on the number of profiles so the kuid can be displayed on two lines with a 150px width and the profiles badges may not be all shown
  - Most of the time, the kuid and the username can be displayed one next to the other if we don't display the profile information there
  
IMO: 
We could display the kuid | username (if exists) without the profiles
And add an additionnal and easy to use filter above the list to search on a profile (like in the profile section to search on the roles)
That would allow us to always display user on a single line and that would make easier to search users by profiles

**Comment by Njuelle** [comment]
Honestly, having the profiles displayed in this list is really useful, I suggest something like this :
image

**Comment by Njuelle** [comment]
final result
image

**Review by jenow — APPROVED** [review]

**Review by Aschen — APPROVED** [review]

**Pull request merged**
