### PR TITLE
Simpler environment management

### PR DESCRIPTION
**Pull request by xbill82**
## What does this PR do ?
Refactors the environment management, fixing some small issues and preparing the ground for some bigger refactors.

### How should this be manually tested?

- At the first page load, pay attention to the small logo and spinner at the center of the screen. They should be nicely centered.
- Create a valid connection (e.g. to your local kuzzle) and ensure the AC properly connects to it
- Create an invalid connection (with a random IP) and take a look at the error page it displays
- Switch between the two environments and ensure the AC smoothly switches from one to the other.

### CODE REVIEW

**Comment by berthieresteban** [comment]
Create ''local' environment
Create a fake 'test' environment
Switch between
On 'test' environment we are on the unable to connect to kuzzle server with the spinner
Delete 'test' env
We can't delete 'test' env, the modal stay on the screen after validating the environment name
The selectbox behind the modal switch to 'null'
The console display some errors:
  - `Error: Cannot connect to a null environment. To reset connection, use the RESET mutation.`
  - `Uncaught (in promise) Error: Unable to execute request: not connected to a Kuzzle server.`

**Comment by berthieresteban** [comment]
Using a fake 'test' env
On trying to connect page
Update the environment name
Get a non explicit line  `[Object Event]`
image

**Comment by berthieresteban** [comment]
The environment name in the select must be cut 
image

**Comment by berthieresteban** [comment]
When trying to connect to a fake 'test' environment
Update the environment name of the 'local' environment
The select switch to the 'local' environment and connect us and push us on the index page while we were trying to connect to the 'test' environment

**Comment by berthieresteban** [comment]
Same as above on the index page
When connected to the 'local' environment
Update the 'test' environment name change the current connection and push us on trying to connect to test:7512 page

**Comment by berthieresteban** [comment]
When connected to the current 'local' environment,
In the switch we can access the current environment
When trying to delete it
Push on the connection page (login as anonymous or create an admin)
And the modal still present
image

**Comment by berthieresteban** [comment]
environment name on index page should be cut
image

**Comment by berthieresteban** [comment]
Same here we should cut the enrivonment name 
image

**Comment by berthieresteban** [comment]
Username should be cut too 
image

**Comment by xbill82** [comment]
Also, the "Export environments" button doesn't work for me. Do you confirm that?

**Comment by berthieresteban** [comment]
Run kuzzle stack with kourou
Connect to AC on localhost
Try to create first admin
Get an error (console + toast)
Create admin button stay disabled until we reload or click on the current environment in the select env
image

**Comment by berthieresteban** [comment]
> Also, the "Export environments" button doesn't work for me. Do you confirm that?

Yes it doesn't work for me too

**Comment by xbill82** [comment]
Hi @berthieresteban , concerning the errors below

> The console display some errors:
>
>    Error: Cannot connect to a null environment. To reset connection, use the RESET mutation.
>    Uncaught (in promise) Error: Unable to execute request: not connected to a Kuzzle server.

I think we should fix this in the #618 because it will be way easier to do it (the refactored code is much cleaner)

**Comment by xbill82** [comment]
Yo @berthieresteban I've solved the issues that I've tagged with the :+1: emoji. The ones that are tagged with the :rocket: emoji should be solved in the #618 PR.

**Pull request merged**
