### PR TITLE
Make BasicFilter more responsive

### PR DESCRIPTION
**Pull request by morgandruesne**
## What does this PR do ?
this PR makes the basic filter more responsive, so more pleasant and readable on smaller screens.

Normal size : 
image

Screen < 1140px :
image

Also, fix bug of `isRealtime` not exit in `DropdownAction.vue `

### CODE REVIEW

**Comment by berthieresteban** [comment]
Seems nice !
I just think the cross button to remove a condition isn't really visually explicit and too close from the "and" text or button on the second screenshot

**Comment by xbill82** [comment]
Nice one! I agree with Esteban! I'd try to put the cross on the right side of the condition (there is plenty of space)

**Comment by berthieresteban** [comment]
Better like that :)
But again I'm not sure it's enough explicit
On the first screen we understand easily that the cross will remove the entire line
On the second not sure that is the same way because the condition is a sort of bloc on multiple lines
What do you think about an outlined red button with "Remove Condition" ? @xbill82 @morgandruesne

**Comment by morgandruesne** [comment]
With the remove button on the left it looks more natural. What do you think?

**Comment by xbill82** [comment]
I've tried a suggestion, what do you think?

93089835-2ee03c80-f69c-11ea-9bad-9c6d11fb4389

**Review by xbill82 — APPROVED** [review]
Looks clear enough 😄

**Review by Leodau — APPROVED** [review]

**Pull request merged**
