### PR TITLE
Fix impossibility to edit documents with spaces in id (issue #547)

### PR DESCRIPTION
**Pull request by barroudjo**
## What does this PR do ?
Solves https://github.com/kuzzleio/kuzzle-admin-console/issues/547

Removed encodeURIComponent of params from push of new url to router, as it is already done by the router
 
### How should this be manually tested?

  - Step 1 : create a document with a space in its id
  - Step 2 : click on the edit button
  - Step 3 :  check that the document is indeed opened

### Boyscout
In fact all encodeURIComponent in router push params should be removed (there are a few more than this one). But I don't know how to test there are no side effects...

### CODE REVIEW

**Comment by xbill82** [comment]
Thanks for your contribution @barroudjo !
I don't think there are potential side effects in adding `encodeURIComponent` to the router params so we should clean them out. I'm adding this to my backlog.

**Comment by barroudjo** [comment]
@xbill82 Tests are failing ? I didn't notice, where can I see which tests fail ?

**Comment by xbill82** [comment]
@barroudjo we have a TravisCI instance running Cypress.io end-to-end tests

**Comment by barroudjo** [comment]
> @barroudjo we have a TravisCI instance running Cypress.io end-to-end tests

@xbill82  where could I see the logs, so that I can fix the problem ? In the meantime I added commits that remove all encodeURIComponents and decodeURIComponents .

**Pull request merged**
