### PR TITLE
Security refactor

### PR DESCRIPTION
**Pull request by xbill82**
## What does this PR do ?
~depends on #430~

MAKE THE ADMINCONSOLE GREAT AGAIN

This PR refactors the security lists (Users, Profiles and Roles) harmonizing the propagation of the filters with the Data section. 

### How should this be manually tested?

Just take a look around and see if anything is broken

### Boyscout

This PR excludes the `vuex-router-sync` package, that we wanted to discard.

### CODE REVIEW

**Comment by scottinet** [comment]
Welp... I created a new connection, that led me to the `.../#/data` URL, which is a blank page the 1st time it loads.
So, I have to refresh it. Now, I have a "Loading Kuzzle Admin Console" waiting page, and it stays there.

I do have an error in the console, but I don't know if it is relevant:

```
SecurityError: The operation is insecure. vendor.7a9b1797e0f418ba0e2b.js:110
	i/this.connect https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:110:10945
	i.prototype.connect https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:110:18352
	t.connectToEnvironment https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/app.67fe30792fbb043b8dea.js:1:11317
	t.default< https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/app.67fe30792fbb043b8dea.js:1:59632
	g/< https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:110:94029
	T.prototype.dispatch https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:115:3525
	T/this.dispatch https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:115:2723
	t.default< https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/app.67fe30792fbb043b8dea.js:1:59348
	g/< https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:110:94029
	T.prototype.dispatch https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:115:3525
	T/this.dispatch https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/vendor.7a9b1797e0f418ba0e2b.js:115:2723
	<anonymous> https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/app.67fe30792fbb043b8dea.js:1:42898
	a https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/manifest.c917bddacda4eccc4673.js:1:96
	window.webpackJsonp https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/manifest.c917bddacda4eccc4673.js:1:418
	<anonymous> https://deploy-preview-431--kuzzle-backoffice-last.netlify.com/static/js/app.67fe30792fbb043b8dea.js:1:1
```

**Comment by xbill82** [comment]
@scottinet wow.. never seen this. Did you try to build the project on your local machine? Just tryin' to figure out if it's related to Netlify.
Personally, I get the same error on Netlify under Firefox but not under Chromium. Everything goes well locally.
Could also be a CORS-related problem (Firefox uses to be more strict than Chrome on this).

**Comment by scottinet** [comment]
@xbill82 > tried locally, and I experienced neither the problems I spotted earlier with netlify nor the security error in the console. Weird.

**Comment by xbill82** [comment]
@scottinet This CORS problem is due to the fact that the Admin Console is served by Netlify via https  and tries to connect to your local Kuzzle via http. While Chrome tolerates this, Firefox doesn't (which is safer).
We are considering the eventuality of deploying a test Kuzzle in our UAT environment (listening to https requests).

**Comment by benoitvidis** [comment]
selection_009
I loose the left menu when resizing the window

**Pull request merged**
